import { Inter } from "next/font/google";
import { GlobalStyles } from "@/GlobalStyles/GlobalStyles";
import StyledComponentsRegistry from "@/GlobalStyles/registry";
import SessionWrapper from "@/components/SessionWrapper/SessionWrapper";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import Layout from "@/components/Layout/Layout";
config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionWrapper>
        <StyledComponentsRegistry>
          <body className={inter.className}>
            <GlobalStyles />
            <Layout>{children}</Layout>
          </body>
        </StyledComponentsRegistry>
      </SessionWrapper>
    </html>
  );
}
